repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.247
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
