repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: ["--explicit-package-bases", "--ignore-missing-imports"]
        additional_dependencies: ["pydantic", "fastapi", "cloudpickle"]
