repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.8 # specify the version you want to use
    hooks:
      - id: ruff
        args: ["--fix"] # this will auto-fix issues when possible

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: ["--explicit-package-bases"]
        additional_dependencies: ["pydantic", "fastapi"]
